
# painel de controle
painel_controle:
  #   versão do código em execução (DEV / PRD)
  ambiente: DEV
  bl_debug_mode: False
  du_ant: 1

# gravação de logs
nome_completo_arquivo_log:
  diretorio_pai: '{}\INFORMACOES DIARIAS\{}\'
  destino: '{}\INFORMACOES DIARIAS\{}\log-{}-SUBSTITUIR-NOME_{}_{}_{}.txt'

# bancos de dados
postgresql:
  keys:
    # ! DB_NAME E SCHEMA_RAW GENERIOS, FAVOR SUBSITUTIR SE NECESSARIO
    db_name: DB_NAME
    schema_raw: SCHEMA_RAW
    # informações de acesso ao banco
    nome_banco: POSTGRESQL
    username: USERNAME
    password: PASSWORD
    host: HOST
    port: PORT

# exportação de arquivos para lugar na rede
json:
  nome_completo_xpt: '{}\INFORMACOES DIARIAS\{}\{}-SUBSTITUIR-NOME_{}_{}_{}.json'