# painel de controle
painel_controle:
  #   versão do código em execução (DEV / PRD)
  ambiente: DEV
  bl_debug_mode: False

# gravação de logs
nome_completo_arquivo_log:
  diretorio_pai: '{}\INFORMACOES DIARIAS\{}\'
  destino: '{}\INFORMACOES DIARIAS\{}\log-{}-SUBSTITUIR-NOME_{}_{}_{}.txt'

# bancos de dados
postgresql:
  keys:
    # ! DB_NAME E SCHEMA_RAW GENERIOS, FAVOR SUBSITUTIR SE NECESSARIO
    db_name: DB_NAME
    schema_raw: SCHEMA_RAW
    # informações de acesso ao banco
    nome_banco: POSTGRESQL
    username: USERNAME
    password: PASSWORD
    host: HOST
    port: PORT

# envio de alertas por webhooks
webhooks:
  keys:
    # ! URL E ID_CHANNEL GENERIOS, FAVOR SUBSITUTIR SE NECESSARIO
    url: URL
    id_channel: ID_CHANNEL
    # informações de acesso ao webhook
    nome_webhook: WEBHOOK_SLACK
    username: USERNAME
    icon_emoji: ICON_EMOJI
  rotina:
    titulo: TITULO
    mensagem: >
      ROTINA: {} 
      \n \n \t - Executadado em: {}. 
      \n \n \t - Máquina do operador: {} 
      \n \n \t - Sigla operador: {} 
      \n \n \t - Evidências disponíveis em: {} 
      \n \n \t - Logs disponíveis em: {} \n \n \t Abs,
    bl_debug_mode: False

# exportação de arquivos para lugar na rede
json:
  nome_completo_xpt: '{}\INFORMACOES DIARIAS\{}\{}-SUBSTITUIR-NOME_{}_{}_{}.json'